include:
 - ./common/monitoring/docker-compose.yaml
 - ./common/minio/docker-compose.yaml
#  - ./common/vault/docker-compose.yaml
#  - ./common/redis/docker-compose.yaml
 - ./common/db/docker-compose.yaml
#  - ./common/rabbitmq/docker-compose.yaml
#  - ./common/kong/docker-compose.yaml
 - ./common/hasura/docker-compose.yaml
 - ./soullab/docker-compose.yaml


services:
  caddy:
    extends:
      file: common/caddy/docker-compose.yaml
      service: caddy
    volumes:
     - ./soullab:/etc/caddy/soullab

volumes:
  caddy_data:
  caddy_config:
